Soru 1 – Liste Metotları
Bir sınıfta öğrencilerin notları şu şekilde tutuluyor:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
• Listedeki tekrar eden notları silip benzersiz bir liste oluşturun.
• En yüksek ve en düşük notu bulun.
• Notları küçükten büyüğe sıralayın

In [30]:
#Cevap 1 (kendi cevabım)
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
for i in range(len(notlar)-1,-1,-1):
    for j in range(len(notlar)-1,-1,-1):
        if i!=j:
            if notlar[i]==notlar[j]:
                notlar.pop(j)
                break
print(notlar)
print(max(notlar))
print(min(notlar))
notlar.sort()
print(notlar)

        

[100, 76, 85, 92]
100
76
[76, 85, 92, 100]


In [35]:
#Cevap 2
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
set_notlar = list(set(notlar))
print(set_notlar)
print(max(set_notlar))
print(min(set_notlar))
set_notlar.sort()
print(set_notlar)

[100, 92, 85, 76]
100
76
[76, 85, 92, 100]


In [44]:
#Cevap 3
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
benzersiz=[]
list_comp_notlar = [benzersiz.append(i) for i in notlar if i not in benzersiz ]
benzersiz.sort()
print(benzersiz)

[76, 85, 92, 100]


Soru 2 – Sayılar
Bir sayının Armstrong sayısı olup olmadığını kontrol eden bir Python fonksiyonu yazın.
Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar.
Örn: 153 → 1³+5³+3³ = 153



In [12]:
 def armstrong_check(x):
    sayi = str(x)
    armstrong_flag = 0
    for i in sayi:
        armstrong_flag += int(i)**3 
    if armstrong_flag == x:
        return True
    else:
        return False

In [13]:
armstrong_check(153)

True

Soru 3 – Kümeler
Aşağıdaki iki küme verilmiştir:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
• Ortak dilleri bulun.
• Sadece A’da olan dilleri listeleyin.
• İki kümenin birleşimini alfabetik olarak yazdırın.

In [56]:
A = {"Python", "R", "SQL", "Java"} 
B = {"C++", "Python", "JavaScript", "SQL"}
ortak_diller = []
only_A = []
for lang in A:
    if lang in B:
        ortak_diller.append(lang)
    else:
        only_A.append(lang)
tum_kume =set( only_A + ortak_diller + list(B))
tum_kume_sıralı = sorted(tum_kume)
print(tum_kume_sıralı)

['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


Soru 4 – Modüller
• random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin.
• Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın.

In [26]:
import random
import statistics
sayilar=[]
for i in range(10):
    sayilar.append(random.randint(1,101))
print(sayilar)
print(statistics.mean(sayilar))
print(statistics.stdev(sayilar))

[26, 80, 100, 52, 70, 97, 48, 5, 63, 62]
60.3
29.571194692733595


Soru 5 – Fonksiyonlar
kelime_sayacı(metin) adında bir fonksiyon yazın.
Fonksiyon verilen metindeki:
• toplam kelime sayısını
• en uzun kelimeyi
• en sık geçen kelimeyi döndürsün.

In [39]:
def kelime_sayaci(metin):
    toplam_kelime = len(metin.split())
    max_sabit = 0
    sik_sabit = 0
    en_sik_kelime = ""
    en_uzun_kelime = ""
    for i in metin.split():
        if len(i) > max_sabit:
            max_sabit= len(i)
            en_uzun_kelime = i
    for j in metin.split():
        if metin.split().count(j) > sik_sabit:
            sik_sabit= metin.split().count(j)
            en_sik_kelime = j
            
    return toplam_kelime, en_sik_kelime,en_uzun_kelime

In [41]:
toplam_kelime, en_sik_kelime,en_uzun_kelime = kelime_sayaci("Emir bugünü kodlama çalışmakla geçirdi. Emir bugün filme gitti. Emir.")
print(f"Bu metinde toplam {toplam_kelime} tane kelime var, en uzun kelimesi {en_uzun_kelime},en sık geçen kelime ise {en_sik_kelime}")

Bu metinde toplam 10 tane kelime var, en uzun kelimesi çalışmakla,en sık geçen kelime ise Emir


Soru 6 – Gömülü Fonksiyonlar
Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak:
sayilar = [5, 12, 7, 18, 24, 3, 16]
• Sadece çift sayıları filtreleyin.
• Bu sayıların karelerini bulun.
• Karelerini azalan sırada sıralayın.

In [2]:
sayilar = [5, 12, 7, 18, 24, 3, 16]
ciftler = filter(lambda x: x%2==0, sayilar)
kareler = map(lambda x: x**2, ciftler )
sirali_kareler = sorted(kareler)
print(sirali_kareler)

[144, 256, 324, 576]


Soru 7 – Lambda İfadeleri
Aşağıdaki listeyi, her kelimenin uzunluğuna göre küçükten büyüğe sıralayın.
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
Bunu sorted + lambda ile yapın

In [38]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
dict_kelimeler = {}
for i in kelimeler: 
    dict_kelimeler[i] = len(i)
sirali = dict(sorted(dict_kelimeler.items(),key=lambda x: x[1]))
kelimeler_sirali = list(sirali.keys())
print(kelimeler_sirali)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


Soru 8 – Metodlar
Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon
yazın.
Örn: "abc12def3" → 12 + 3 = 15

In [65]:
string = "abc12def3"
gecici= ""
toplam=0
for i in range(len(string)):
    if string[i].isdigit():
        gecici += string[i]
    else:
         if gecici != "":   
            toplam+= int(gecici)
            gecici=""
if gecici != "":
    toplam += int(gecici)

print(toplam)
    

15


Soru 9 – (Ekstra) Numpy 1
10 elemanlı bir numpy dizisi oluşturun.
• Elemanlar 0–50 arasında rastgele sayılar olsun.
• Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun.

In [12]:
import numpy as np
import random
np_dizisi = np.random.randint(0,51,10)
np_ortalama = np.mean(np_dizisi)
np_stdev = np.std(np_dizisi)
np_max= np.amax(np_dizisi)
print(f"Numpy Dizisi {np_dizisi}, Ortalaması {np_ortalama}, Standard Sapması {np_stdev}, Max Değeri {np_max}")

Numpy Dizisi [10 31 32 29 36 20 50  0 18 35], Ortalaması 26.1, Standard Sapması 13.634148304899725, Max Değeri 50


Soru 10 – (Ekstra) Numpy 2
5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin.
• Her sütunun ortalamasını bulun.
• 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun.

In [55]:
array_np = np.random.random((5,5))
ortalama_sutun = np.mean(array_np,axis=1)
yuvarlanmıs = np.round(array_np).astype(int)
print(ortalama_sutun)
print(yuvarlanmıs)

[0.3332615  0.61790247 0.19284178 0.58583435 0.5586843 ]
[[1 0 1 0 0]
 [1 0 1 1 1]
 [0 0 0 0 0]
 [1 0 0 1 1]
 [0 0 1 1 1]]
